imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AcmeHomeBundle/Resources/config/services.yml" }
    - { resource: "@AcmeContactBundle/Resources/config/services.yml" }
    - { resource: "@AcmeActeurBundle/Resources/config/services.yml" }
    - { resource: "@AcmeFilialeBundle/Resources/config/services.yml" }
    - { resource: "@AcmeWorkBundle/Resources/config/services.yml" }

assetic:
    debug:  '%kernel.debug%'
    use_controller: '%kernel.debug%'
    twig:
        functions:
            jpegoptim: ~
    assets:
        jquery: %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
        material_icons:
            inputs:
                 - https://fonts.googleapis.com/icon?family=Material+Icons
    bundles: [ MaterializeBundle ]



# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: Fr
    images_directory: '%kernel.root_dir%/../web/uploads/images'
    mailer_user:     fabienruault@gmail.com
    mailer_password: vbmqvpcuxtzeadng

framework:
       #esi: ~
       #translator: { fallbacks: ['%locale%'] }
       secret: '%secret%'
       router:
           resource: '%kernel.project_dir%/app/config/routing.yml'
           strict_requirements: ~
       form: ~
       csrf_protection: ~
       validation: { enable_annotations: true }
       #serializer: { enable_annotations: true }
       templating:
           engines: ['twig']
       default_locale: '%locale%'
       trusted_hosts: ~
       session:
           # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
           handler_id: session.handler.native_file
           save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
       fragments: ~
       http_method_override: true
       assets: ~
       php_errors:
           log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
                - '@Curiosity26AngularMaterialBundle/Resources/Form/material_1_layout.html.twig'
doctrine:
    dbal:
        driver: pdo_sqlite
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        path: '%database_path%'
    orm:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "test@test.com"
        sender_name: "ja"
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: 'KnpPaginatorBundle:Pagination:sliding.html.twig'
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig'


#MaterializeBundle
materialize:
        local_cdn: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js'

