<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDhp1exw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDhp1exw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDhp1exw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDhp1exw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDhp1exw\appProdProjectContainer();
