<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assetic.asset_manager' shared service.

include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Loader/FormulaLoaderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/assetic-bundle/Factory/Loader/ConfigurationLoader.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/TwigFormulaLoader.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Cache/ConfigCache.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Loader/CachedFormulaLoader.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Resource/ResourceInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/assetic-bundle/Factory/Resource/ConfigurationResource.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Resource/IteratorResourceInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Resource/DirectoryResource.php';
include_once $this->targetDirs[3].'/vendor/symfony/assetic-bundle/Factory/Resource/DirectoryResource.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Resource/CoalescingDirectoryResource.php';
include_once $this->targetDirs[3].'/vendor/symfony/assetic-bundle/Factory/Resource/CoalescingDirectoryResource.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/AssetManager.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php';

$this->services['assetic.asset_manager'] = $instance = new \Assetic\Factory\LazyAssetManager(${($_ = isset($this->services['assetic.asset_factory']) ? $this->services['assetic.asset_factory'] : $this->getAssetic_AssetFactoryService()) && false ?: '_'}, array('config' => new \Symfony\Bundle\AsseticBundle\Factory\Loader\ConfigurationLoader(), 'twig' => new \Assetic\Factory\Loader\CachedFormulaLoader(new \Assetic\Extension\Twig\TwigFormulaLoader(${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.assetic']) ? $this->services['monolog.logger.assetic'] : $this->load(__DIR__.'/getMonolog_Logger_AsseticService.php')) && false ?: '_'}), new \Assetic\Cache\ConfigCache(($this->targetDirs[0].'/assetic/config')), true)));

$a = ${($_ = isset($this->services['templating.loader']) ? $this->services['templating.loader'] : $this->load(__DIR__.'/getTemplating_LoaderService.php')) && false ?: '_'};

$instance->addResource(new \Symfony\Bundle\AsseticBundle\Factory\Resource\ConfigurationResource(array('jquery' => array(0 => array(0 => ($this->targetDirs[3].'/app/../vendor/components/jquery/jquery.min.js')), 1 => array(), 2 => array()), 'material_icons' => array(0 => array(0 => 'https://fonts.googleapis.com/icon?family=Material+Icons'), 1 => array(), 2 => array()))), 'config');
$instance->addResource(new \Symfony\Bundle\AsseticBundle\Factory\Resource\CoalescingDirectoryResource(array(0 => new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, 'MaterializeBundle', ($this->targetDirs[3].'/app/Resources/MaterializeBundle/views'), '/\\.[^.]+\\.twig$/'), 1 => new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, 'MaterializeBundle', ($this->targetDirs[3].'/vendor/evheniy/materialize-bundle/Evheniy/MaterializeBundle/Resources/views'), '/\\.[^.]+\\.twig$/'))), 'twig');
$instance->addResource(new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, '', ($this->targetDirs[3].'/app/Resources/views'), '/\\.[^.]+\\.twig$/'), 'twig');

return $instance;
