acme_acteur_entityacteurs:
    resource: "@AcmeActeurBundle/Resources/config/routing/entityacteurs.php"
    prefix:   /entityacteurs


acme_acteur_homepage:
    path:     /Acteurs
    defaults: { _controller: AcmeActeurBundle:Acteur:index }
