<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4goye1y\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4goye1y/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4goye1y.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4goye1y\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4goye1y\appDevDebugProjectContainer();
