<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKpzp2ui\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKpzp2ui/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKpzp2ui.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKpzp2ui\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKpzp2ui\appDevDebugProjectContainer();
