<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9zv6m2d\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9zv6m2d/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9zv6m2d.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9zv6m2d\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9zv6m2d\appDevDebugProjectContainer();
